################################################
# Server configurations
################################################
server:
  connector:
    # Changing port is available for embedded server only
    # Is is not possible to change port for deploying application on external server
    port: 8080


################################################
# Application (global) configurations
################################################
application:
  # License path
  # Absolute or relative path to GroupDocs license file
  licensePath:
  # Host name or ip for server instance
  hostAddress:

################################################
# Common configurations
################################################
common:
  # File rewriting on document uploading
  # Set false to keep both files
  # Set true to replace files with same name
  rewrite: true
  # Page navigation
  # Set false to disable document navigation (go to next, previous, last and first page)
  pageSelector: true
  # Document download
  # Set false to disable document download
  download: true
  # Document upload
  # Set false to disable document upload
  upload: true
  # Document print
  # Set false to disable document print
  print: true
  # File browser
  # Set false to disable document browse
  browse: true
  # Set false to disable right mouse click
  enableRightClick: true

################################################
# GroupDocs.Editor configurations
################################################
editor:
  # Files directory path
  # Absolute or relative path to files directory
  filesDirectory: DocumentSamples
  # Fonts path
  # Absolute path to custom fonts directory
  fontsDirectory:
  # Default document
  # Absolute path to default document
  defaultDocument:
  # Enable / disable new document creation
  createNewFile: true